import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";
import Providers from "@/app/Providers";
import { Nav } from "@/components/nav/Nav";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

//   const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
//   });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html
      lang="fa" dir="rtl"
      suppressHydrationWarning
      className={`${poppins.className} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col" >

        <Providers>
          <Toaster />
          <Nav />
          {children}
        </Providers>
      </body>

    </html>

  );
}
